version: "3.4"

services:
#   tool_portainer:
#     container_name: "docker_portainer"
#     image: portainer/portainer
#     restart: always
#     ports:
#       - "9000:9000"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./portainer:/data portainer/portainer
#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: ./docker/app/Dockerfile
#    ports:
#      - 8000:8000
#    env_file:
#      - .env
#    depends_on:
#      - database

  database:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
